name: All in One
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp






    - name: Get D-PTVPhilippines.m3u8
      run: |
        touch ./D-PTVPhilippines.m3u8
        sudo cat >./D-PTVPhilippines.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.dailymotion.com/video/x5cr6b9)
        EOL

    - name: Get Y-DZRHNewsTelevision.m3u8
      run: |
        touch ./Y-DZRHNewsTelevision.m3u8
        sudo cat >./Y-DZRHNewsTelevision.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@DZRHTV/live)
        EOL

    - name: Get Y-NET25TV.m3u8
      run: |
        touch ./Y-NET25TV.m3u8
        sudo cat >./Y-NET25TV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@NET25TV/live)
        EOL

    - name: Get Y-PTVPhilippines.m3u8
      run: |
        touch ./Y-PTVPhilippines.m3u8
        sudo cat >./Y-PTVPhilippines.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@ptvph/live)
        EOL

    - name: Get Y-TeleRadyo.m3u8
      run: |
        touch ./Y-TeleRadyo.m3u8
        sudo cat >./Y-TeleRadyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@TeleRadyo/live)
        EOL

    - name: Get Y-TeleRadyo.m3u8
      run: |
        touch ./Y-abscbnnews.m3u8
        sudo cat >./Y-abscbnnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@abscbnnews/live)
        EOL

    - name: Get Y-UNTVNewsandRescue.m3u8
      run: |
        touch ./Y-UNTVNewsandRescue.m3u8
        sudo cat >./Y-UNTVNewsandRescue.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@UNTVNewsandRescue/live)
        EOL

    - name: Get Y-marinai.m3u8
      run: |
        touch ./Y-marinai.m3u8
        sudo cat >./Y-marinai.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/marinai/live)
        EOL

    - name: Get Y-PlayMedia10.m3u8
      run: |
        touch ./Y-PlayMedia10.m3u8
        sudo cat >./Y-PlayMedia10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@PlayMedia10/live)
        EOL

    - name: Get Y-abscbnentertainment.m3u8
      run: |
        touch ./Y-abscbnentertainment.m3u8
        sudo cat >./Y-abscbnentertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g --no-live-from-start https://www.youtube.com/channel/UCstEtN0pgOmCf02EdXsGChw/live)
        EOL
        
    - name: Get twitch.m3u8
      run: |
        touch ./twitch.m3u8
        sudo cat >./twitch.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g --no-live-from-start https://azrotv.com/m3u8/kuwaittv/?id=kwtv1)
        EOL

    - name: Get twitch1.m3u8
      run: |
        touch ./twitch1.m3u8
        sudo cat >./twitch1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://azrotv.com/m3u8/kuwaittv/?id=kwtv1)
        EOL




        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b IPTV
        git add .
        git commit -m "Update IPTV"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin IPTV
