name: All in One
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get Y-abscbnentertainment.m3u8
      run: |
        touch ./Y-abscbnentertainment.m3u8
        sudo cat >./Y-abscbnentertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g -f 92 https://www.youtube.com/abscbnentertainment/live)
        EOL


        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b IPTV
        git add .
        git commit -m "Update IPTV"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin IPTV
