name: All in One
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl






    - name: Get Y-abscbnentertainment.m3u8
      run: |
        touch ./Y-abscbnentertainment.m3u8
        sudo cat >./Y-abscbnentertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g -F S8Zt6cB_NPU 1La4QzGeaaQ -xNN-bJQ4vI i6fWG4FxDZw https://www.youtube.com/abscbnentertainment/live)
        EOL


        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b IPTV
        git add .
        git commit -m "Update IPTV"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin IPTV
