name: All in One
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp






    - name: Get Y-DZRHNewsTelevision.m3u8
      run: |
        touch ./Y-DZRHNewsTelevision.m3u8
        sudo cat >./Y-DZRHNewsTelevision.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@DZRHTV/live)
        EOL

    - name: Get Y-NET25TV.m3u8
      run: |
        touch ./Y-NET25TV.m3u8
        sudo cat >./Y-NET25TV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@NET25TV/live)
        EOL

    - name: Get Y-PTVPhilippines.m3u8
      run: |
        touch ./Y-PTVPhilippines.m3u8
        sudo cat >./Y-PTVPhilippines.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@ptvph/live)
        EOL

    - name: Get Y-TeleRadyo.m3u8
      run: |
        touch ./Y-TeleRadyo.m3u8
        sudo cat >./Y-TeleRadyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@TeleradyoSerbisyo/live)
        EOL

    - name: Get Y-abscbnnews.m3u8
      run: |
        touch ./Y-abscbnnews.m3u8
        sudo cat >./Y-abscbnnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@abscbnnews/live)
        EOL

    - name: Get Y-NEWS-TV5.m3u8
      run: |
        touch ./Y-NEWS-TV5.m3u8
        sudo cat >./Y-NEWS-TV5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/channel/UCGEbMwiX774cseKvJqF9R2g/live)
        EOL

    - name: Get Y-UNTVNewsandRescue.m3u8
      run: |
        touch ./Y-UNTVNewsandRescue.m3u8
        sudo cat >./Y-UNTVNewsandRescue.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@UNTVNewsandRescue/live)
        EOL

    - name: Get Y-marinai.m3u8
      run: |
        touch ./Y-marinai.m3u8
        sudo cat >./Y-marinai.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/channel/UCZbpK_Lgctew3YNELlG2ecw/live)
        EOL
      
    - name: Get Alrai-TV.m3u8
      run: |
        touch ./Alrai-TV.m3u8
        sudo cat >./Alrai-TV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=908285,RESOLUTION=854x480,CODECS="avc1.77.30,mp4a.40.2",CLOSED-CAPTIONS=NONE
        $(yt-dlp -g --no-live-from-start https://ltvl.vercel.app/alraimedia/livestream)
        EOL
        
    - name: Get TOYOR-ALJANAH.m3u8
      run: |
        touch ./TOYOR-ALJANAH.m3u8
        sudo cat >./TOYOR-ALJANAH.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g --no-live-from-start https://7t2.000.pe/youtube/?id=UCZbpK_Lgctew3YNELlG2ecw)
        EOL



        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b IPTV
        git add .
        git commit -m "Update IPTV"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin IPTV
