name: All in One
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp






    - name: Get D-PTVPhilippines.m3u8
      run: |
        touch ./D-PTVPhilippines.m3u8
        sudo cat >./D-PTVPhilippines.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.dailymotion.com/video/x5cr6b9)
        EOL

    - name: Get Y-DZRHNewsTelevision.m3u8
      run: |
        touch ./Y-DZRHNewsTelevision.m3u8
        sudo cat >./Y-DZRHNewsTelevision.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@DZRHTV/live)
        EOL

    - name: Get Y-NET25TV.m3u8
      run: |
        touch ./Y-NET25TV.m3u8
        sudo cat >./Y-NET25TV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@NET25TV/live)
        EOL

    - name: Get Y-PTVPhilippines.m3u8
      run: |
        touch ./Y-PTVPhilippines.m3u8
        sudo cat >./Y-PTVPhilippines.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@ptvph/live)
        EOL

    - name: Get Y-TeleRadyo.m3u8
      run: |
        touch ./Y-TeleRadyo.m3u8
        sudo cat >./Y-TeleRadyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@TeleRadyo/live)
        EOL

    - name: Get Y-TeleRadyo.m3u8
      run: |
        touch ./Y-abscbnnews.m3u8
        sudo cat >./Y-abscbnnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@abscbnnews/live)
        EOL

    - name: Get Y-UNTVNewsandRescue.m3u8
      run: |
        touch ./Y-UNTVNewsandRescue.m3u8
        sudo cat >./Y-UNTVNewsandRescue.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@UNTVNewsandRescue/live)
        EOL

    - name: Get Y-marinai.m3u8
      run: |
        touch ./Y-marinai.m3u8
        sudo cat >./Y-marinai.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/marinai/live)
        EOL

    - name: Get Y-PlayMedia10.m3u8
      run: |
        touch ./Y-PlayMedia10.m3u8
        sudo cat >./Y-PlayMedia10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/@PlayMedia10/live)
        EOL

    - name: Get Y-abscbnentertainment.m3u8
      run: |
        touch ./Y-abscbnentertainment.m3u8
        sudo cat >./Y-abscbnentertainment.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g --no-live-from-start https://www.youtube.com/channel/UCstEtN0pgOmCf02EdXsGChw/live)
        EOL
        
    - name: Get KUWAIT-1.m3u8
      run: |
        touch ./KUWAIT-1.m3u8
        sudo cat >./KUWAIT-1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KUWAIT-2.m3u8
      run: |
        touch ./KUWAIT-2.m3u8
        sudo cat >./KUWAIT-2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=250000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtktv2ta.cdn.mangomolo.com/ktv2/smil:ktv2.stream.smil/chunklist_b250000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=550000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtktv2ta.cdn.mangomolo.com/ktv2/smil:ktv2.stream.smil/chunklist_b550000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=1500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtktv2ta.cdn.mangomolo.com/ktv2/smil:ktv2.stream.smil/chunklist_b1500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtktv2ta.cdn.mangomolo.com/ktv2/smil:ktv2.stream.smil/chunklist_b3500000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-AlMajlis.m3u8
      run: |
        touch ./KTV-AlMajlis.m3u8
        sudo cat >./KTV-AlMajlis.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtalmta.cdn.mangomolo.com/alm/smil:alm.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtalmta.cdn.mangomolo.com/alm/smil:alm.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtalmta.cdn.mangomolo.com/alm/smil:alm.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtalmta.cdn.mangomolo.com/alm/smil:alm.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-Drama.m3u8
      run: |
        touch ./KTV-Drama.m3u8
        sudo cat >./KTV-Drama.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtkbta.cdn.mangomolo.com/kb/smil:kb.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtkbta.cdn.mangomolo.com/kb/smil:kb.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtkbta.cdn.mangomolo.com/kb/smil:kb.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtkbta.cdn.mangomolo.com/kb/smil:kb.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-AlQurain.m3u8
      run: |
        touch ./KTV-AlQurain.m3u8
        sudo cat >./KTV-AlQurain.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtktvaqta.cdn.mangomolo.com/ktvaq/smil:ktvaq.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtktvaqta.cdn.mangomolo.com/ktvaq/smil:ktvaq.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtktvaqta.cdn.mangomolo.com/ktvaq/smil:ktvaq.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtktvaqta.cdn.mangomolo.com/ktvaq/smil:ktvaq.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-Arabe.m3u8
      run: |
        touch ./KTV-Arabe.m3u8
        sudo cat >./KTV-Arabe.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=250000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtktvata.cdn.mangomolo.com/ktva/smil:ktva.stream.smil/chunklist_b250000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=550000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtktvata.cdn.mangomolo.com/ktva/smil:ktva.stream.smil/chunklist_b550000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=1600000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtktvata.cdn.mangomolo.com/ktva/smil:ktva.stream.smil/chunklist_b1600000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtktvata.cdn.mangomolo.com/ktva/smil:ktva.stream.smil/chunklist_b3500000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-Sport.m3u8
      run: |
        touch ./KTV-Sport.m3u8
        sudo cat >./KTV-Sport.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-Sport-Plus.m3u8
      run: |
        touch ./KTV-Sport-Plus.m3u8
        sudo cat >./KTV-Sport-Plus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=350000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist_b350000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=900000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist_b900000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist_b3500000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=8000000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist_b8000000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get KTV-Ethraa.m3u8
      run: |
        touch ./KTV-Ethraa.m3u8
        sudo cat >./KTV-Ethraa.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=250000,NAME="240p",RESOLUTION=426x240
        $(yt-dlp -g --no-live-from-start https://kwtethta.cdn.mangomolo.com/eth/smil:eth.stream.smil/chunklist_b250000_t64MjQwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=550000,NAME="360p",RESOLUTION=640x360
        $(yt-dlp -g --no-live-from-start https://kwtethta.cdn.mangomolo.com/eth/smil:eth.stream.smil/chunklist_b550000_t64MzYwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=1600000,NAME="720p",RESOLUTION=1280x720
        $(yt-dlp -g --no-live-from-start https://kwtethta.cdn.mangomolo.com/eth/smil:eth.stream.smil/chunklist_b1600000_t64NzIwcA==.m3u8)
        #EXT-X-STREAM-INF:BANDWIDTH=3500000,NAME="1080p",RESOLUTION=1920x1080
        $(yt-dlp -g --no-live-from-start https://kwtethta.cdn.mangomolo.com/eth/smil:eth.stream.smil/chunklist_b3500000_t64MTA4MHA=.m3u8)
        EOL

    - name: Get Rotana-Classic.m3u8
      run: |
        touch ./Rotana-Classic.m3u8
        sudo cat >./Rotana-Classic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g --no-live-from-start http://azrotv.com/m3u8/ro/?id=comedy)
        EOL
        




        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b IPTV
        git add .
        git commit -m "Update IPTV"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin IPTV
