name: Delete File

on: [push] # يمكنك تعديل هذا الحدث حسب الاحتياج

jobs:
  delete_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete file
      run: |
        git config user.email "you@example.com"
        git config user.name "Your Name"
        git rm path/to/your/file.txt
        git commit -m "Delete file.txt"
        git push
