name: Generate M3U8 and Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-generate-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to generate M3U8
      run: |
        chmod +x ./app.sh
        ./app.sh

    - name: Check if app.m3u8 was created
      run: |
        if [ -f app.m3u8 ]; then
          echo "app.m3u8 exists."
        else
          echo "app.m3u8 does not exist."
          exit 1
        fi

    - name: Commit and push if changed
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add app.m3u8
        git diff --staged --quiet || git commit -m "Automated m3u8 update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
