name: test
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
     
    - name: Get test.m3u8
      run: |
        touch ./test.m3u8
        sudo cat >./test.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1568726
        $(youtube-dl -g https://www.youtube.com/@PlayMedia10/live)
        EOL
     
    - name: git add
      run: |
        git init
        git config --local user.name "kubbar"
        git config --local user.email "@gmail.com"
        git checkout -b test
        git add .
        git commit -m "Update test"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin test
